# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae8b26a525ecbba39f7e9790ec7823934eb7f25f86f2c25ad00ff0fc58c9682f9c632640c437d8b4a9a58bddbfc4958d88982fed47c96f9baed5d1544b122613

test:
  secret_key_base: 099920a23506d4553570672f6998b5ca1d373c2c52461b2fe74ab95afd0c2305db79bf1923c8dff207158d5281f13019d00f1a1c71822ac56ced1ba776c75c38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
